---
- hosts: all
  tasks:
    - name: Install configurations and plugins
      include_role:
        name: '{{ playbook_dir }}'
      with_items: '{{ apps }}'
      loop_control:
        loop_var: app
      tags:
        - ansidot-packages
        - ansidot-git
        - ansidot-directories
        - ansidot-dotfiles
        - packages
        - git
        - directories
        - dotfiles
