---
# tasks file for ansidot

- name: '{{ app.name }} - check required packages are installed'
  package:
    name: '{{ app.packages }}'
  when: app.packages is defined
  tags: packages

- name: '{{ app.name }} - install Git repositories'
  include_tasks: git.yml
  with_items: '{{ app.git }}'
  loop_control:
    label: '{{ item.repo }}'
  when: app.git is defined
  tags: git

- name: '{{ app.name }} - install dotfiles'
  include_tasks: dotfiles.yml
  with_items: '{{ app.dotfiles }}'
  loop_control:
    label: '{{ item.path }}'
  when: app.dotfiles is defined
  tags: dotfiles

- name: '{{ app.name }} - set directory permissions'
  file:
    path: '{{ item.path }}'
    state: directory
    recurse: true
    mode: '{{ item.mode | default(omit) }}'
  with_items: '{{ app.directories }}'
  loop_control:
    label: '{{ item.path }}'
  when: app.directories is defined
  tags: directories
